In [1]:
import pandas as pd
import numpy as np

a=np.random.randn(5,10)
df=pd.DataFrame(a)

In [2]:
a

array([[ 0.25667056, -0.54613993, -0.53358287,  1.6901468 ,  1.71452835,
         1.06650029,  0.42516294,  0.01132299, -0.8453335 , -0.1417125 ],
       [ 0.26840916,  0.63369548,  1.58034111, -2.68132071, -0.34309488,
         1.17044296, -1.37417243,  2.03242369, -1.23752365, -0.81402051],
       [ 1.67947016, -0.81944661, -2.36651522,  0.24932272, -0.39210187,
        -0.24161567, -0.21745463,  0.20701174,  0.03480106, -1.25807151],
       [-1.57912305, -0.58028377, -1.74454584, -0.61049945,  0.53314022,
         1.51806752,  0.66769863, -0.25394667, -0.67776064, -0.9001706 ],
       [ 1.51912649, -0.93449435, -2.01671768,  0.41377538, -1.80908068,
        -0.76608966, -2.35199004, -0.27889756, -0.32385296, -1.20976817]])

In [3]:
df

,0,1,2,3,4,5,6,7,8,9
0,0.256671,-0.546140,-0.533583,1.690147,1.714528,1.066500,0.425163,0.011323,-0.845334,-0.141712
1,0.268409,0.633695,1.580341,-2.681321,-0.343095,1.170443,-1.374172,2.032424,-1.237524,-0.814021
2,1.679470,-0.819447,-2.366515,0.249323,-0.392102,-0.241616,-0.217455,0.207012,0.034801,-1.258072
3,-1.579123,-0.580284,-1.744546,-0.610499,0.533140,1.518068,0.667699,-0.253947,-0.677761,-0.900171
4,1.519126,-0.934494,-2.016718,0.413775,-1.809081,-0.766090,-2.351990,-0.278898,-0.323853,-1.209768